version: "3.7"

services:
    api:
        build:
          context: .
          dockerfile: Lobster.Adventure/Dockerfile
        ports:
          - "8080:80"
        environment:
          ASPNETCORE_ENVIRONMENT: Development
          DB_CONNECTION_STRING: mongodb:27017
          DB_NAME: lobster
          TABLE_ADVENTURE_NAME: adventure
          TABLE_ADVENTURE_RESULT_NAME: adventure_result
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        depends_on:
          - mongodb

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
          MONGO_INITDB_DATABASE: lobster
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
          - 27017:27017
        volumes:
          - ./mongo-init/:/docker-entrypoint-initdb.d/:ro