global using Lobster.Adventure.Logic.Models;
global using Lobster.Adventure.Logic.Interfaces.Services;
global using Lobster.Adventure.Logic.Interfaces.Services.Create;
global using static Lobster.Adventure.Logic.Settings.Constants;
global using Lobster.Adventure.DataAccess.Interfaces.Repositories;
global using Lobster.Adventure.DataAccess.Entities;
global using Lobster.Adventure.Logic.Interfaces.Mapping;
global using System.Text.Json;
global using Lobster.Adventure.DataAccess.Exceptions;
global using Lobster.Adventure.Logic.Interfaces.Services.Save;
global using System.ComponentModel.DataAnnotations;