global using Xunit;
global using Lobster.Adventure.Logic.Models;
global using Lobster.Adventure.Controllers;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Lobster.Adventure.Logic.Interfaces.Services.Create;
global using Lobster.Adventure.Logic.Services;
global using Lobster.Adventure.Logic.Tests.Fixtures;
global using FluentAssertions;
